### ISSUE TITLE
写了个爬虫，然后配合你这个相册，出了点小问题

### ISSUE THREAD

**Issue by ghost** [sk1418/gallery#1]
RT
爬了4W+张图片，然后一次性导入，看了下生成的index.html有21M那么大，导致浏览的时候直接转圈等半天。。。

**Comment by ghost** [comment]
还有一点就是，在store目录下，我放了一个Beauty的目录，目录下还有个子目录，该相册没有显示

**Comment by sk1418** [comment]
- 4W 张图, 考虑爬完了分几个文件夹吧,  你都弄一起一页显示当然吃力了
- store目录下只看子目录的一层. 不做多层查找. 目录类似相册里的专辑, 没有再往下一层, 毕竟不是树. 而且生成的缩略图都在每一个"专辑"的里面.

这两个我觉得gallery这边没什么可以fix的.... 或者你有什么建议?
