### ISSUE TITLE
How about compressing the picture?

### ISSUE THREAD

**Issue by wintercoder** [sk1418/gallery#3]
额 英文难打直接上中文把。
手机拍的图片4M大，虽然首页列表有缩略图，但点进去就是4M大，加载慢还耗流量。
如果再建一个压缩后的图片目录，点进具体图片的时候就显示压缩后的，点下载按钮就下载原图，这样在网速不快的地方会流畅很多。如何？

**Comment by sk1418** [comment]
你说的可以考虑. 我也查看了下那个lightgallery js api, 它们也支持download url是单独的. 
但是如果细想下, 还有些细小的东西要考虑比如, 应该对于图像文件进行判断,  定义个threshold, 大于这个size的, 才压缩等. 这对于文件保存, 同步, 等带来点复杂度. 目前我个人使用上, 跟dropbox连用, 直接一个脚本rsync那边需要的目录到这里, 就都有了 (gh-page branch). 这些就必须要改. 但总的来说, 功能实现起来并不复杂.

还有一个是, 我做这个初衷是想弄个最简单基于git的网络相册, 所以github page就成了我的目标. 但是, github page有个非强制性的1G容量限制. 如果超过1G会收到官方的警告信, 来缩减repo的size.  如果不缩减会怎样, 并不知道, (官方没说会强制进行关闭, 缩减等). 当然这个可以通过串联多个repo来解决. 总之, gallery并不是一个保存高清大图的最好办法, 4M的图, 也就2000几百张. 你可以看下我的gh-page, 图都不大. 

你说的这个功能等没事的时候可以考虑弄下. 如果你能提交pull request, 更好. :+1:    现在每天业余时间多用于写图里那些字了...呵呵
