### ISSUE TITLE
你好，请问你知道这个情况是什么原因吗？

### ISSUE THREAD

**Issue by rankaiyx** [sk1418/gallery#5]
你好，请问你知道这个情况是什么原因吗？我试着运行了一下，返回如下结果：

Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
==================== RESTART: D:\gallery-master\build.py ====================
[INFO] 
[INFO] =============================================================================
[INFO] All templates have been loaded
[INFO] =============================================================================
[INFO] =============================================================================
[INFO] Creating gallery for store\two\
Traceback (most recent call last):
  File "D:\gallery-master\build.py", line 199, in <module>
    create_htmls(incr)
  File "D:\gallery-master\build.py", line 145, in create_htmls
    all_htmls = get_main_html_dict(incremental)
  File "D:\gallery-master\build.py", line 135, in get_main_html_dict
    gallery_html = create_gallery_html(image_dir, incremental)
  File "D:\gallery-master\build.py", line 122, in create_gallery_html
    gallery_name = image_dir.split('/')[-2]
IndexError: list index out of range
>>>

**Comment by rankaiyx** [comment]
是否跟操作系统有关？我是用的Win7

**Comment by rankaiyx** [comment]
果然如此 用Ubuntu & python3 生成网页成功

**Comment by sk1418** [comment]
我没有windows 系统可以测试, 对这个系统也不是很熟悉, 不方便debug, 很高兴你的问题得以解决. 如果你能fix在windows系统下的问题就更好. 
我看那个错误信息好像是路径的问题, linux用的`/`, 但是windows却是`\\`

**Comment by rankaiyx** [comment]
可以了，按你说的那样，把122行和140行的/改成\\，Win7&Python3.5.4下生成网页成功。打开网页看了，也没问题。

**Comment by rankaiyx** [comment]
可以了，按你说的那样，把122行和140行的/改成\\\，Win7&Python3.5.4下生成网页成功。打开网页看了，也没问题。

**Comment by rankaiyx** [comment]
![image](https://user-images.githubusercontent.com/39045067/65587327-44a2b080-dfb8-11e9-8732-a3db3476a633.png)

进一步的，把122行和140行的代码改成这样，经验证，Ubuntu和Win7都可成功运行。
参考 https://docs.python.org/2/library/os.path.html

**Comment by sk1418** [comment]
thx, can you please create a pull request?

**Comment by rankaiyx** [comment]
I'll work on this
